name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust_version: [stable, "1.39.0"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup default ${{ matrix.rust_version }}

    - name: Build
      run: cargo build --all --verbose

    - name: Run tests
      run: cargo test --all --verbose

    - name: Rustfmt and Clippy
      run: |
        cargo fmt -- --check
        cargo clippy
      if: matrix.rust_version == 'stable'

  publish:
    # Publishing goes when we create a new git tag on the repo
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    # XXX: this job must execute only if all checks pass!
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }})
